// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package todo

import (
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID        uuid.UUID
	Title     string
	Content   string
	CreatedAt time.Time
}
